name: MoeMaps
main: cn.whiteg.moemaps.MoeMaps
version: 1.1
api-version: 1.13
author: MoeWhite
depend: [ Vault ]
softdepend: [ Residence, MMOCore ]
commands:
  moemaps:
    description: The is MoeMaps Command
    aliases: [ 'mm','mmap','maps' ]